FROM n8nio/n8n:1.28.0

USER root
RUN apk add --no-cache su-exec

ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV N8N_HOST=0.0.0.0
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
ENV EXECUTIONS_PROCESS=main
ENV N8N_ENCRYPTION_KEY=supersecretkey123

EXPOSE 5678

CMD ["n8n", "start"]
